/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as StudyWritingRouteImport } from './routes/study.writing'
import { Route as LibraryDeckIdRouteImport } from './routes/library.$deckId'
import { Route as DeckOwnerSlugRouteImport } from './routes/deck.$owner.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyWritingRoute = StudyWritingRouteImport.update({
  id: '/study/writing',
  path: '/study/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryDeckIdRoute = LibraryDeckIdRouteImport.update({
  id: '/library/$deckId',
  path: '/library/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckOwnerSlugRoute = DeckOwnerSlugRouteImport.update({
  id: '/deck/$owner/$slug',
  path: '/deck/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library/$deckId': typeof LibraryDeckIdRoute
  '/study/writing': typeof StudyWritingRoute
  '/library/': typeof LibraryIndexRoute
  '/study/': typeof StudyIndexRoute
  '/deck/$owner/$slug': typeof DeckOwnerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library/$deckId': typeof LibraryDeckIdRoute
  '/study/writing': typeof StudyWritingRoute
  '/library': typeof LibraryIndexRoute
  '/study': typeof StudyIndexRoute
  '/deck/$owner/$slug': typeof DeckOwnerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library/$deckId': typeof LibraryDeckIdRoute
  '/study/writing': typeof StudyWritingRoute
  '/library/': typeof LibraryIndexRoute
  '/study/': typeof StudyIndexRoute
  '/deck/$owner/$slug': typeof DeckOwnerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/review'
    | '/sitemap.xml'
    | '/library/$deckId'
    | '/study/writing'
    | '/library/'
    | '/study/'
    | '/deck/$owner/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/review'
    | '/sitemap.xml'
    | '/library/$deckId'
    | '/study/writing'
    | '/library'
    | '/study'
    | '/deck/$owner/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/review'
    | '/sitemap.xml'
    | '/library/$deckId'
    | '/study/writing'
    | '/library/'
    | '/study/'
    | '/deck/$owner/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ReviewRoute: typeof ReviewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LibraryDeckIdRoute: typeof LibraryDeckIdRoute
  StudyWritingRoute: typeof StudyWritingRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  DeckOwnerSlugRoute: typeof DeckOwnerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/writing': {
      id: '/study/writing'
      path: '/study/writing'
      fullPath: '/study/writing'
      preLoaderRoute: typeof StudyWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$deckId': {
      id: '/library/$deckId'
      path: '/library/$deckId'
      fullPath: '/library/$deckId'
      preLoaderRoute: typeof LibraryDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$owner/$slug': {
      id: '/deck/$owner/$slug'
      path: '/deck/$owner/$slug'
      fullPath: '/deck/$owner/$slug'
      preLoaderRoute: typeof DeckOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ReviewRoute: ReviewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LibraryDeckIdRoute: LibraryDeckIdRoute,
  StudyWritingRoute: StudyWritingRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  DeckOwnerSlugRoute: DeckOwnerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
