/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryDeckIdRouteImport } from './routes/library.$deckId'
import { Route as StudyWritingIndexRouteImport } from './routes/study.writing.index'
import { Route as StudyGrammarIndexRouteImport } from './routes/study.grammar.index'
import { Route as StudyWritingHistoryRouteImport } from './routes/study.writing.history'
import { Route as DeckOwnerSlugRouteImport } from './routes/deck.$owner.$slug'
import { Route as StudyWritingHistoryIdRouteImport } from './routes/study.writing.history.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryDeckIdRoute = LibraryDeckIdRouteImport.update({
  id: '/library/$deckId',
  path: '/library/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyWritingIndexRoute = StudyWritingIndexRouteImport.update({
  id: '/study/writing/',
  path: '/study/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyGrammarIndexRoute = StudyGrammarIndexRouteImport.update({
  id: '/study/grammar/',
  path: '/study/grammar/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyWritingHistoryRoute = StudyWritingHistoryRouteImport.update({
  id: '/study/writing/history',
  path: '/study/writing/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckOwnerSlugRoute = DeckOwnerSlugRouteImport.update({
  id: '/deck/$owner/$slug',
  path: '/deck/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyWritingHistoryIdRoute = StudyWritingHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudyWritingHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/exam': typeof ExamRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library/$deckId': typeof LibraryDeckIdRoute
  '/library/': typeof LibraryIndexRoute
  '/study/': typeof StudyIndexRoute
  '/deck/$owner/$slug': typeof DeckOwnerSlugRoute
  '/study/writing/history': typeof StudyWritingHistoryRouteWithChildren
  '/study/grammar/': typeof StudyGrammarIndexRoute
  '/study/writing/': typeof StudyWritingIndexRoute
  '/study/writing/history/$id': typeof StudyWritingHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/exam': typeof ExamRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library/$deckId': typeof LibraryDeckIdRoute
  '/library': typeof LibraryIndexRoute
  '/study': typeof StudyIndexRoute
  '/deck/$owner/$slug': typeof DeckOwnerSlugRoute
  '/study/writing/history': typeof StudyWritingHistoryRouteWithChildren
  '/study/grammar': typeof StudyGrammarIndexRoute
  '/study/writing': typeof StudyWritingIndexRoute
  '/study/writing/history/$id': typeof StudyWritingHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/exam': typeof ExamRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library/$deckId': typeof LibraryDeckIdRoute
  '/library/': typeof LibraryIndexRoute
  '/study/': typeof StudyIndexRoute
  '/deck/$owner/$slug': typeof DeckOwnerSlugRoute
  '/study/writing/history': typeof StudyWritingHistoryRouteWithChildren
  '/study/grammar/': typeof StudyGrammarIndexRoute
  '/study/writing/': typeof StudyWritingIndexRoute
  '/study/writing/history/$id': typeof StudyWritingHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/exam'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/library/$deckId'
    | '/library/'
    | '/study/'
    | '/deck/$owner/$slug'
    | '/study/writing/history'
    | '/study/grammar/'
    | '/study/writing/'
    | '/study/writing/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/exam'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/library/$deckId'
    | '/library'
    | '/study'
    | '/deck/$owner/$slug'
    | '/study/writing/history'
    | '/study/grammar'
    | '/study/writing'
    | '/study/writing/history/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/exam'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/library/$deckId'
    | '/library/'
    | '/study/'
    | '/deck/$owner/$slug'
    | '/study/writing/history'
    | '/study/grammar/'
    | '/study/writing/'
    | '/study/writing/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ExamRoute: typeof ExamRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LibraryDeckIdRoute: typeof LibraryDeckIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  DeckOwnerSlugRoute: typeof DeckOwnerSlugRoute
  StudyWritingHistoryRoute: typeof StudyWritingHistoryRouteWithChildren
  StudyGrammarIndexRoute: typeof StudyGrammarIndexRoute
  StudyWritingIndexRoute: typeof StudyWritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$deckId': {
      id: '/library/$deckId'
      path: '/library/$deckId'
      fullPath: '/library/$deckId'
      preLoaderRoute: typeof LibraryDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/writing/': {
      id: '/study/writing/'
      path: '/study/writing'
      fullPath: '/study/writing/'
      preLoaderRoute: typeof StudyWritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/grammar/': {
      id: '/study/grammar/'
      path: '/study/grammar'
      fullPath: '/study/grammar/'
      preLoaderRoute: typeof StudyGrammarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/writing/history': {
      id: '/study/writing/history'
      path: '/study/writing/history'
      fullPath: '/study/writing/history'
      preLoaderRoute: typeof StudyWritingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$owner/$slug': {
      id: '/deck/$owner/$slug'
      path: '/deck/$owner/$slug'
      fullPath: '/deck/$owner/$slug'
      preLoaderRoute: typeof DeckOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/writing/history/$id': {
      id: '/study/writing/history/$id'
      path: '/$id'
      fullPath: '/study/writing/history/$id'
      preLoaderRoute: typeof StudyWritingHistoryIdRouteImport
      parentRoute: typeof StudyWritingHistoryRoute
    }
  }
}

interface StudyWritingHistoryRouteChildren {
  StudyWritingHistoryIdRoute: typeof StudyWritingHistoryIdRoute
}

const StudyWritingHistoryRouteChildren: StudyWritingHistoryRouteChildren = {
  StudyWritingHistoryIdRoute: StudyWritingHistoryIdRoute,
}

const StudyWritingHistoryRouteWithChildren =
  StudyWritingHistoryRoute._addFileChildren(StudyWritingHistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExamRoute: ExamRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LibraryDeckIdRoute: LibraryDeckIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  DeckOwnerSlugRoute: DeckOwnerSlugRoute,
  StudyWritingHistoryRoute: StudyWritingHistoryRouteWithChildren,
  StudyGrammarIndexRoute: StudyGrammarIndexRoute,
  StudyWritingIndexRoute: StudyWritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
