INSERT INTO public.shop_items (id, kind, name, description, price, payload, icon, accent, active, sort_order) VALUES
('bundle.corte_marionetes','bundle','Corte das Marionetes','O palco gótico do teatro eterno desperta. A Corte das Marionetes reúne cosméticos nascidos do espetáculo sombrio: cortinas de veludo rubro, máscaras de porcelana quebrada, fios de prata e uma soberana que conduz seus súditos de madeira e cera. Elegância macabra para quem enxerga beleza nos fios que movem o mundo.',900,'{"items":["cosmetic.aura.corte_marionetes","cosmetic.frame.coroa_marionete","cosmetic.effect.teatro_marionetes","cosmetic.veil.veu_marionete","cosmetic.table.mesa_marionetes","cosmetic.streak_flame.chama_marionete","cosmetic.enemy_seal.selo_marionete","cosmetic.victory_splash.ascensao_marionete"],"rarity":"mitico"}','crown','crimson',true,10),
('cosmetic.aura.corte_marionetes','cosmetic','Aura da Corte','Um halo de fios de prata e pétalas de rosa carmim giram ao redor do avatar como um espetáculo eterno.',360,'{"key":"corte_marionetes","slot":"decoration"}','sparkles','crimson',true,351),
('cosmetic.frame.coroa_marionete','cosmetic','Coroa da Marionete','Moldura circular de porcelana quebrada, rosas rubras e fios de prata que prendem uma máscara de bailarina no ápice.',390,'{"key":"coroa_marionete","slot":"nameplate"}','crown','crimson',true,352),
('cosmetic.effect.teatro_marionetes','cosmetic','Teatro das Marionetes','Capa de perfil: um palco barroco em ruínas, cortinas de veludo rubro, máscaras caídas e um holofote solitário iluminando o vazio.',420,'{"key":"teatro_marionetes","slot":"effect"}','moon','crimson',true,353),
('cosmetic.veil.veu_marionete','cosmetic','Véu da Marionete','Moldura de carta em veludo carmim, renda negra, máscaras de porcelana nos cantos e fios de marionete suspensos.',320,'{"key":"veu_marionete","slot":"veil"}','layers','crimson',true,354),
('cosmetic.table.mesa_marionetes','cosmetic','Mesa da Corte','Mesa de revisão do teatro eterno: palco gótico, máscaras de porcelana, pétalas rubras e holofote dramático sobre a carta.',320,'{"bundle":"corte_marionetes","key":"mesa_marionetes","rarity":"mitico","slot":"table"}','layout','crimson',true,355),
('cosmetic.streak_flame.chama_marionete','cosmetic','Chama da Marionete','Sua sequência diária arde em veludo carmim e porcelana, envolta pelos fios que nunca se soltam.',300,'{"key":"chama_marionete","slot":"streak_flame"}','flame','crimson',true,356),
('cosmetic.enemy_seal.selo_marionete','cosmetic','Selo da Marionete','As cartas inimigas recebem uma máscara de porcelana trincada com lágrimas de cera e fios de prata cruzando o selo.',350,'{"key":"selo_marionete","slot":"enemy_seal"}','sparkles','crimson',true,357),
('cosmetic.victory_splash.ascensao_marionete','cosmetic','Ascensão da Marionete','Ao vencer, a soberana dos fios ascende em um holoforte branco, pétalas rubras e máscaras de porcelana explodem em reverência.',420,'{"key":"ascensao_marionete","slot":"victory_splash"}','trophy','crimson',true,358)
ON CONFLICT (id) DO UPDATE SET kind=EXCLUDED.kind, name=EXCLUDED.name, description=EXCLUDED.description, price=EXCLUDED.price, payload=EXCLUDED.payload, icon=EXCLUDED.icon, accent=EXCLUDED.accent, active=EXCLUDED.active, sort_order=EXCLUDED.sort_order;