INSERT INTO public.shop_items (id, kind, name, description, price, payload, icon, accent, active, sort_order) VALUES
('bundle.piscina_infinita','bundle','Piscina Infinita','Um clube de verão infinito no crepúsculo do airi: azulejos azul-piscina, boias douradas, peixes bobos de óculos e drinks escorrendo gelo. Luxo com humor.',500,'{"items":["cosmetic.aura.piscina_infinita","cosmetic.frame.coroa_piscina","cosmetic.veil.veu_piscina","cosmetic.table.mesa_piscina","cosmetic.streak_flame.chama_piscina","cosmetic.enemy_seal.selo_piscina","cosmetic.victory_splash.ascensao_piscina"],"rarity":"epic"}','crown','cyan',true,11),
('cosmetic.aura.piscina_infinita','cosmetic','Aura da Piscina Infinita','Anel de água azul-piscina com peixes bobos nadando em círculos dourados ao redor do avatar.',350,'{"key":"piscina_infinita","slot":"decoration"}','sparkles','cyan',true,300),
('cosmetic.frame.coroa_piscina','cosmetic','Coroa da Piscina','Aro dourado de piscina com rosas metalizadas e gotas de água — a coroa do verão infinito.',380,'{"key":"coroa_piscina","slot":"nameplate"}','crown','amber',true,301),
('cosmetic.veil.veu_piscina','cosmetic','Véu da Piscina','Verso das cartas com uma boia rosa e um peixinho dourado de óculos, flutuando em azulejos azul-piscina.',320,'{"key":"veu_piscina","slot":"veil"}','layers','pink',true,302),
('cosmetic.table.mesa_piscina','cosmetic','Mesa da Piscina Infinita','Mesa de revisão em uma infinity pool ao crepúsculo: azulejos turquesa, boias douradas e peixes bobos.',420,'{"bundle":"piscina_infinita","key":"mesa_piscina","rarity":"epic","slot":"table"}','layout','cyan',true,303),
('cosmetic.streak_flame.chama_piscina','cosmetic','Chama Tropical','Chama de streak com chapéu de palha, drink de coco e um peixe espirrando água.',300,'{"key":"chama_piscina","slot":"streak_flame"}','flame','amber',true,304),
('cosmetic.enemy_seal.selo_piscina','cosmetic','Selo Solar','Selo redondo com um sol dourado de óculos e um peixinho bocejando na onda.',280,'{"key":"selo_piscina","slot":"enemy_seal"}','sun','amber',true,305),
('cosmetic.victory_splash.ascensao_piscina','cosmetic','Splash de Verão','Ao vencer, você mergulha triunfal na piscina infinita junto com peixes bobos e boias douradas.',400,'{"key":"ascensao_piscina","slot":"victory_splash"}','trophy','cyan',true,306)
ON CONFLICT (id) DO UPDATE SET kind=EXCLUDED.kind, name=EXCLUDED.name, description=EXCLUDED.description, price=EXCLUDED.price, payload=EXCLUDED.payload, icon=EXCLUDED.icon, accent=EXCLUDED.accent, active=EXCLUDED.active, sort_order=EXCLUDED.sort_order;