INSERT INTO public.shop_items (id, kind, name, description, price, payload, icon, accent, active, sort_order) VALUES
('bundle.nevoa_espiritual','bundle','Névoa Espiritual','Sob a lua do santuário esquecido, lâminas espirituais flutuam em chamas azuis. A coleção Névoa Espiritual reúne cosméticos nascidos do outro lado do véu: torii em ruínas, pétalas brancas, fogo-fátuo cobalto e uma guardiã coroada pelo luar. Serenidade e poder para quem estuda em silêncio.',1100,'{"items":["cosmetic.effect.santuario_espiritual","cosmetic.overlay.petalas_espectrais","cosmetic.aura.nevoa_espiritual","cosmetic.frame.coroa_nevoa","cosmetic.veil.veu_espectral","cosmetic.companion.cordeiro_espiritual","cosmetic.streak_flame.chama_espiritual","cosmetic.enemy_seal.selo_espiritual","cosmetic.title.guardia_nevoa","cosmetic.victory_splash.ascensao_espiritual","cosmetic.table.mesa_espiritual"]}','crown','azure',true,8),
('cosmetic.aura.nevoa_espiritual','cosmetic','Aura da Névoa Espiritual','Um anel de névoa cobalto, pétalas brancas e fogo-fátuo gira ao redor do avatar. A marca de quem cruzou o véu.',350,'{"key":"nevoa_espiritual","slot":"decoration"}','sparkles','azure',true,330),
('cosmetic.frame.coroa_nevoa','cosmetic','Coroa da Névoa','Tiara de prata e ouro pálido com esmalte cobalto, safiras e flores espirituais. Ornamento da guardiã do santuário.',380,'{"key":"coroa_nevoa","slot":"nameplate"}','crown','azure',true,331),
('cosmetic.effect.santuario_espiritual','cosmetic','Santuário Espiritual','Capa de perfil: torii em ruínas sob a lua cheia, névoa azul, lanternas acesas e chamas espirituais flutuando.',420,'{"key":"santuario_espiritual","slot":"effect"}','moon','azure',true,332),
('cosmetic.overlay.petalas_espectrais','cosmetic','Pétalas Espectrais','Overlay animado: pétalas brancas e brasas azuis caem lentamente por cima da sua capa.',300,'{"key":"petalas_espectrais","slot":"overlay"}','sparkles','azure',true,333),
('cosmetic.veil.veu_espectral','cosmetic','Véu Espectral','Moldura de cartão em prata e safira, com labaredas azuis e flores brancas contornando o estudo.',320,'{"key":"veu_espectral","slot":"veil"}','moon','azure',true,334),
('cosmetic.companion.cordeiro_espiritual','cosmetic','Cordeiro Espiritual','Companheiro: um cordeiro espectral de chifres luminosos e juba de fogo azul. Guia das almas na névoa.',600,'{"key":"cordeiro_espiritual","slot":"companion"}','sparkles','azure',true,335),
('cosmetic.streak_flame.chama_espiritual','cosmetic','Chama Espiritual','Sua chama de sequência vira fogo-fátuo cobalto, com pétalas subindo a cada dia seguido.',300,'{"key":"chama_espiritual","slot":"streak_flame"}','flame','azure',true,336),
('cosmetic.enemy_seal.selo_espiritual','cosmetic','Selo Espiritual','Cartas inimigas ganham um sigilo de santuário girando atrás da carta, selado a cada acerto.',350,'{"key":"selo_espiritual","slot":"enemy_seal"}','sparkles','azure',true,337),
('cosmetic.title.guardia_nevoa','cosmetic','Guardião da Névoa','Título animado com gradiente cobalto exibido logo abaixo do seu nome no perfil.',300,'{"key":"guardia_nevoa","slot":"title"}','crown','azure',true,338),
('cosmetic.victory_splash.ascensao_espiritual','cosmetic','Ascensão Espiritual','Ao vencer um duelo, a tela explode em raios azuis, lâminas espirituais e pétalas.',420,'{"key":"ascensao_espiritual","slot":"victory_splash"}','trophy','azure',true,339),
('cosmetic.table.mesa_espiritual','cosmetic','Altar da Névoa','Mesa de revisão da Névoa Espiritual: brasão de lótus na carta, moldura de safira, santuário ao fundo e feedback azul a cada acerto.',300,'{"bundle":"nevoa_espiritual","key":"mesa_espiritual","rarity":"mitico","slot":"table"}','layers','azure',true,340)
ON CONFLICT (id) DO UPDATE SET kind=EXCLUDED.kind, name=EXCLUDED.name, description=EXCLUDED.description, price=EXCLUDED.price, payload=EXCLUDED.payload, icon=EXCLUDED.icon, accent=EXCLUDED.accent, active=EXCLUDED.active, sort_order=EXCLUDED.sort_order;