INSERT INTO public.shop_items (id, kind, name, description, price, payload, icon, accent, active, sort_order) VALUES
('bundle.princesa_espinho_prata','bundle','Princesa Espinho de Prata','Uma princesa selada sob renda negra, prata viva e velas azuis que nunca se apagam. O bundle Princesa Espinho de Prata transforma o perfil e a revisão em um rito glacial: espinhos de prata, capela congelada, brasões de safira e explosões de gelo ritualístico.',900,'{"items":["cosmetic.aura.espinho_prata","cosmetic.frame.coroa_espinho_prata","cosmetic.effect.capela_vigilia","cosmetic.veil.veu_espinho_prata","cosmetic.table.mesa_vigilia_prateada","cosmetic.streak_flame.chama_vigilia","cosmetic.enemy_seal.olho_vigilia","cosmetic.victory_splash.ascensao_vigilia"],"rarity":"mitico"}','crown','azure',true,9),
('cosmetic.aura.espinho_prata','cosmetic','Aura Espinho de Prata','Um halo ritual de espinhos prateados, renda negra e velas-fantasma azuis envolve o avatar como um juramento congelado.',360,'{"key":"espinho_prata","slot":"decoration"}','sparkles','azure',true,341),
('cosmetic.frame.coroa_espinho_prata','cosmetic','Coroa Espinho de Prata','Tiara de espinhos de prata com safiras profundas e chama azul no ápice. Um símbolo de realeza corrompida e vigilante.',390,'{"key":"coroa_espinho_prata","slot":"nameplate"}','crown','azure',true,342),
('cosmetic.effect.capela_vigilia','cosmetic','Capela da Vigília','Capa de perfil: arcos góticos de gelo negro, névoa baixa e dezenas de velas azuis queimando no silêncio.',420,'{"key":"capela_vigilia","slot":"effect"}','moon','azure',true,343),
('cosmetic.veil.veu_espinho_prata','cosmetic','Véu do Espinho de Prata','Moldura de carta em prata viva, renda negra e safiras frias, como um relicário amaldiçoado do inverno.',320,'{"key":"veu_espinho_prata","slot":"veil"}','layers','azure',true,344),
('cosmetic.table.mesa_vigilia_prateada','cosmetic','Mesa da Vigília Prateada','Mesa de revisão da princesa: brasão de safira, ferro prateado e fogo azul sagrado sobre um altar escuro.',320,'{"bundle":"princesa_espinho_prata","key":"mesa_vigilia_prateada","rarity":"mitico","slot":"table"}','layout','azure',true,345),
('cosmetic.streak_flame.chama_vigilia','cosmetic','Chama da Vigília','Sua sequência diária queima com fogo-fantasma azul preso por espinhos de prata.',300,'{"key":"chama_vigilia","slot":"streak_flame"}','flame','azure',true,346),
('cosmetic.enemy_seal.olho_vigilia','cosmetic','Olho da Vigília','As cartas inimigas recebem um selo arcano com íris azul e correntes de prata girando atrás da carta.',350,'{"key":"olho_vigilia","slot":"enemy_seal"}','sparkles','azure',true,347),
('cosmetic.victory_splash.ascensao_vigilia','cosmetic','Ascensão da Vigília','Ao vencer, espinhos de prata, renda negra e fragmentos de gelo explodem a partir de um núcleo azul ritual.',420,'{"key":"ascensao_vigilia","slot":"victory_splash"}','trophy','azure',true,348)
ON CONFLICT (id) DO UPDATE SET kind=EXCLUDED.kind, name=EXCLUDED.name, description=EXCLUDED.description, price=EXCLUDED.price, payload=EXCLUDED.payload, icon=EXCLUDED.icon, accent=EXCLUDED.accent, active=EXCLUDED.active, sort_order=EXCLUDED.sort_order;